name: salad_bar
description: سلطة بار - نظام إدارة الطلبات
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  path_provider: ^2.1.4
  share_plus: ^10.1.4
  file_picker: ^8.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
